/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as DashboardTeamsRouteImport } from './routes/dashboard.teams'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardResumesRouteImport } from './routes/dashboard.resumes'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as UUsernameIndexRouteImport } from './routes/u.$username.index'
import { Route as DashboardTeamsIndexRouteImport } from './routes/dashboard.teams.index'
import { Route as UUsernameResumeSlugRouteImport } from './routes/u.$username.$resumeSlug'
import { Route as PTeamSlugProjectSlugRouteImport } from './routes/p.$teamSlug.$projectSlug'
import { Route as DashboardTeamsTeamIdRouteImport } from './routes/dashboard.teams.$teamId'
import { Route as DashboardResumesResumeIdRouteImport } from './routes/dashboard.resumes.$resumeId'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard.projects.new'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardResumesResumeIdTreeRouteImport } from './routes/dashboard.resumes.$resumeId.tree'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/team/$slug',
  path: '/team/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamsRoute = DashboardTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumesRoute = DashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRoute,
} as any)
const DashboardTeamsIndexRoute = DashboardTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeamsRoute,
} as any)
const UUsernameResumeSlugRoute = UUsernameResumeSlugRouteImport.update({
  id: '/$resumeSlug',
  path: '/$resumeSlug',
  getParentRoute: () => UUsernameRoute,
} as any)
const PTeamSlugProjectSlugRoute = PTeamSlugProjectSlugRouteImport.update({
  id: '/p/$teamSlug/$projectSlug',
  path: '/p/$teamSlug/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamsTeamIdRoute = DashboardTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => DashboardTeamsRoute,
} as any)
const DashboardResumesResumeIdRoute =
  DashboardResumesResumeIdRouteImport.update({
    id: '/$resumeId',
    path: '/$resumeId',
    getParentRoute: () => DashboardResumesRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumesResumeIdTreeRoute =
  DashboardResumesResumeIdTreeRouteImport.update({
    id: '/tree',
    path: '/tree',
    getParentRoute: () => DashboardResumesResumeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRouteWithChildren
  '/team/$slug': typeof TeamSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/resumes/$resumeId': typeof DashboardResumesResumeIdRouteWithChildren
  '/dashboard/teams/$teamId': typeof DashboardTeamsTeamIdRoute
  '/p/$teamSlug/$projectSlug': typeof PTeamSlugProjectSlugRoute
  '/u/$username/$resumeSlug': typeof UUsernameResumeSlugRoute
  '/dashboard/teams/': typeof DashboardTeamsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/dashboard/resumes/$resumeId/tree': typeof DashboardResumesResumeIdTreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/resumes/$resumeId': typeof DashboardResumesResumeIdRouteWithChildren
  '/dashboard/teams/$teamId': typeof DashboardTeamsTeamIdRoute
  '/p/$teamSlug/$projectSlug': typeof PTeamSlugProjectSlugRoute
  '/u/$username/$resumeSlug': typeof UUsernameResumeSlugRoute
  '/dashboard/teams': typeof DashboardTeamsIndexRoute
  '/u/$username': typeof UUsernameIndexRoute
  '/dashboard/resumes/$resumeId/tree': typeof DashboardResumesResumeIdTreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/teams': typeof DashboardTeamsRouteWithChildren
  '/team/$slug': typeof TeamSlugRoute
  '/u/$username': typeof UUsernameRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/resumes/$resumeId': typeof DashboardResumesResumeIdRouteWithChildren
  '/dashboard/teams/$teamId': typeof DashboardTeamsTeamIdRoute
  '/p/$teamSlug/$projectSlug': typeof PTeamSlugProjectSlugRoute
  '/u/$username/$resumeSlug': typeof UUsernameResumeSlugRoute
  '/dashboard/teams/': typeof DashboardTeamsIndexRoute
  '/u/$username/': typeof UUsernameIndexRoute
  '/dashboard/resumes/$resumeId/tree': typeof DashboardResumesResumeIdTreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/projects'
    | '/dashboard/resumes'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/team/$slug'
    | '/u/$username'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/resumes/$resumeId'
    | '/dashboard/teams/$teamId'
    | '/p/$teamSlug/$projectSlug'
    | '/u/$username/$resumeSlug'
    | '/dashboard/teams/'
    | '/u/$username/'
    | '/dashboard/resumes/$resumeId/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/projects'
    | '/dashboard/resumes'
    | '/dashboard/settings'
    | '/team/$slug'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/resumes/$resumeId'
    | '/dashboard/teams/$teamId'
    | '/p/$teamSlug/$projectSlug'
    | '/u/$username/$resumeSlug'
    | '/dashboard/teams'
    | '/u/$username'
    | '/dashboard/resumes/$resumeId/tree'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/projects'
    | '/dashboard/resumes'
    | '/dashboard/settings'
    | '/dashboard/teams'
    | '/team/$slug'
    | '/u/$username'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/dashboard/resumes/$resumeId'
    | '/dashboard/teams/$teamId'
    | '/p/$teamSlug/$projectSlug'
    | '/u/$username/$resumeSlug'
    | '/dashboard/teams/'
    | '/u/$username/'
    | '/dashboard/resumes/$resumeId/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  TeamSlugRoute: typeof TeamSlugRoute
  UUsernameRoute: typeof UUsernameRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PTeamSlugProjectSlugRoute: typeof PTeamSlugProjectSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/team/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams': {
      id: '/dashboard/teams'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof DashboardTeamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resumes': {
      id: '/dashboard/resumes'
      path: '/resumes'
      fullPath: '/dashboard/resumes'
      preLoaderRoute: typeof DashboardResumesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/dashboard/teams/': {
      id: '/dashboard/teams/'
      path: '/'
      fullPath: '/dashboard/teams/'
      preLoaderRoute: typeof DashboardTeamsIndexRouteImport
      parentRoute: typeof DashboardTeamsRoute
    }
    '/u/$username/$resumeSlug': {
      id: '/u/$username/$resumeSlug'
      path: '/$resumeSlug'
      fullPath: '/u/$username/$resumeSlug'
      preLoaderRoute: typeof UUsernameResumeSlugRouteImport
      parentRoute: typeof UUsernameRoute
    }
    '/p/$teamSlug/$projectSlug': {
      id: '/p/$teamSlug/$projectSlug'
      path: '/p/$teamSlug/$projectSlug'
      fullPath: '/p/$teamSlug/$projectSlug'
      preLoaderRoute: typeof PTeamSlugProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teams/$teamId': {
      id: '/dashboard/teams/$teamId'
      path: '/$teamId'
      fullPath: '/dashboard/teams/$teamId'
      preLoaderRoute: typeof DashboardTeamsTeamIdRouteImport
      parentRoute: typeof DashboardTeamsRoute
    }
    '/dashboard/resumes/$resumeId': {
      id: '/dashboard/resumes/$resumeId'
      path: '/$resumeId'
      fullPath: '/dashboard/resumes/$resumeId'
      preLoaderRoute: typeof DashboardResumesResumeIdRouteImport
      parentRoute: typeof DashboardResumesRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resumes/$resumeId/tree': {
      id: '/dashboard/resumes/$resumeId/tree'
      path: '/tree'
      fullPath: '/dashboard/resumes/$resumeId/tree'
      preLoaderRoute: typeof DashboardResumesResumeIdTreeRouteImport
      parentRoute: typeof DashboardResumesResumeIdRoute
    }
  }
}

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardResumesResumeIdRouteChildren {
  DashboardResumesResumeIdTreeRoute: typeof DashboardResumesResumeIdTreeRoute
}

const DashboardResumesResumeIdRouteChildren: DashboardResumesResumeIdRouteChildren =
  {
    DashboardResumesResumeIdTreeRoute: DashboardResumesResumeIdTreeRoute,
  }

const DashboardResumesResumeIdRouteWithChildren =
  DashboardResumesResumeIdRoute._addFileChildren(
    DashboardResumesResumeIdRouteChildren,
  )

interface DashboardResumesRouteChildren {
  DashboardResumesResumeIdRoute: typeof DashboardResumesResumeIdRouteWithChildren
}

const DashboardResumesRouteChildren: DashboardResumesRouteChildren = {
  DashboardResumesResumeIdRoute: DashboardResumesResumeIdRouteWithChildren,
}

const DashboardResumesRouteWithChildren =
  DashboardResumesRoute._addFileChildren(DashboardResumesRouteChildren)

interface DashboardTeamsRouteChildren {
  DashboardTeamsTeamIdRoute: typeof DashboardTeamsTeamIdRoute
  DashboardTeamsIndexRoute: typeof DashboardTeamsIndexRoute
}

const DashboardTeamsRouteChildren: DashboardTeamsRouteChildren = {
  DashboardTeamsTeamIdRoute: DashboardTeamsTeamIdRoute,
  DashboardTeamsIndexRoute: DashboardTeamsIndexRoute,
}

const DashboardTeamsRouteWithChildren = DashboardTeamsRoute._addFileChildren(
  DashboardTeamsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardResumesRoute: typeof DashboardResumesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamsRoute: typeof DashboardTeamsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardResumesRoute: DashboardResumesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamsRoute: DashboardTeamsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface UUsernameRouteChildren {
  UUsernameResumeSlugRoute: typeof UUsernameResumeSlugRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const UUsernameRouteChildren: UUsernameRouteChildren = {
  UUsernameResumeSlugRoute: UUsernameResumeSlugRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const UUsernameRouteWithChildren = UUsernameRoute._addFileChildren(
  UUsernameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  TeamSlugRoute: TeamSlugRoute,
  UUsernameRoute: UUsernameRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PTeamSlugProjectSlugRoute: PTeamSlugProjectSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
