import type { CategorySlug } from "../../lib/designs";

// Single source of truth: maps (category, design) -> the showcase source
// filename (without extension) under apps/www/src/pages/showcase/.
// `registry.tsx` derives the React component map from this; `scripts/
// build-registry.ts` reads it as a Node script. Keep this file React-free.
export const SOURCE_FILES: Partial<
  Record<CategorySlug, Record<string, string>>
> = {
  auth: {
    login: "login",
    onboarding: "onboarding",
    waitlist: "waitlist",
    "check-email": "auth-check-email",
    "inset-login": "inset-login",
    "centered-signin": "auth-centered-signin",
    "centered-signup": "auth-centered-signup",
    "left-signin": "auth-left-signin",
    "right-signin": "auth-right-signin",
    "glass-signup": "auth-glass-signup",
    "otp-verify": "auth-otp-verify",
    "reset-password": "auth-reset-password",
    "two-factor": "auth-two-factor",
    "magic-link-sent": "auth-magic-link-sent",
  },
  "empty-states": {
    "inbox-zero": "empty-inbox-zero",
    "no-results": "empty-no-results",
    "first-project": "empty-first-project",
    "end-of-feed": "empty-end-of-feed",
    "no-team": "empty-no-team",
    trash: "empty-trash",
    "404": "empty-404",
    maintenance: "empty-maintenance",
    "no-files": "empty-no-files",
    offline: "empty-offline",
  },
  cards: {
    "stat-tile": "card-stat-tile",
    profile: "card-profile",
    pricing: "card-pricing",
    product: "card-product",
    invoice: "card-invoice",
    task: "card-task",
    event: "card-event",
    integration: "card-integration",
    media: "card-media",
    "payment-method": "card-payment-method",
  },
  forms: {
    "workspace-settings": "forms-workspace-settings",
    "invite-teammates": "forms-invite-teammates",
    notifications: "forms-notifications",
    "api-key": "forms-api-key",
  },
  tables: {
    invoices: "table-invoices",
    members: "table-members",
    orders: "table-orders",
    logs: "table-logs",
    "api-keys": "table-api-keys",
    inventory: "table-inventory",
    issues: "table-issues",
    transactions: "table-transactions",
    "audit-log": "table-audit-log",
  },
  filters: {
    toolbar: "filter-toolbar",
    faceted: "filter-faceted",
    chips: "filter-chips",
    sidebar: "filter-sidebar",
  },
  layouts: {
    "workspace-rail": "sidebars-workspace-rail",
    "mini-rail": "sidebars-mini-rail",
    "docs-tree": "sidebars-docs-tree",
    "inbox-rail": "sidebars-inbox-rail",
    "app-shell": "layouts-app-shell",
    "two-pane": "layouts-two-pane",
    "three-pane": "layouts-three-pane",
    "split-resizable": "layouts-split-resizable",
    "focus-mode": "layouts-focus-mode",
    "floating-toolbar": "layouts-floating-toolbar",
    "canvas-tools": "layouts-canvas-tools",
    "bottom-nav": "layouts-bottom-nav",
  },
  dashboards: {
    "metrics-overview": "dashboards-metrics-overview",
    usage: "dashboards-usage",
    analytics: "dashboards-analytics",
    home: "dashboards-home",
    revenue: "dashboards-revenue",
    services: "dashboards-services",
    engineering: "dashboards-engineering",
    support: "dashboards-support",
    market: "dashboards-market",
  },
  settings: {
    profile: "settings-profile",
    appearance: "settings-appearance",
    billing: "settings-billing",
    integrations: "settings-integrations",
    security: "settings-security",
    permissions: "settings-permissions",
    branding: "settings-branding",
    localization: "settings-localization",
    webhooks: "settings-webhooks",
    privacy: "settings-privacy",
    developer: "settings-developer",
    sso: "settings-sso",
  },
  modals: {
    "confirm-delete": "modals-confirm-delete",
    "share-link": "modals-share-link",
    "upload-files": "modals-upload-files",
    "command-palette": "modals-command-palette",
    feedback: "modals-feedback",
    shortcuts: "modals-shortcuts",
    upgrade: "modals-upgrade",
    export: "modals-export",
    "create-workspace": "modals-create-workspace",
    "two-factor": "modals-two-factor",
  },
  charts: {
    "revenue-area": "charts-revenue-area",
    "cohort-heatmap": "charts-cohort-heatmap",
    funnel: "charts-funnel",
    gauges: "charts-gauges",
    "bar-grouped": "charts-bar-grouped",
    "line-multi": "charts-line-multi",
    donut: "charts-donut",
    scatter: "charts-scatter",
    waterfall: "charts-waterfall",
  },
  timelines: {
    audit: "timelines-audit",
    notifications: "timelines-notifications",
    changelog: "timelines-changelog",
    commits: "timelines-commits",
    approvals: "timelines-approvals",
    "pull-request": "timelines-pull-request",
    "pr-ops-console": "timelines-pr-ops-console",
    releases: "timelines-releases",
    "status-page": "timelines-status-page",
    deploys: "timelines-deploys",
    "inbox-thread": "timelines-inbox-thread",
    "activity-feed": "timelines-activity-feed",
  },
  calendars: {
    month: "calendars-month",
    week: "calendars-week",
    agenda: "calendars-agenda",
    "date-range": "calendars-date-range",
    timezone: "calendars-timezone",
    availability: "calendars-availability",
    mini: "calendars-mini",
    "year-heatmap": "calendars-year-heatmap",
    recurring: "calendars-recurring",
    holidays: "calendars-holidays",
  },
  profile: {
    hero: "profile-hero",
    "hover-card": "profile-hover-card",
    "team-grid": "profile-team-grid",
    directory: "profile-directory",
    "compact-card": "profile-compact-card",
    "org-chart": "profile-org-chart",
    skills: "profile-skills",
    "presence-rail": "profile-presence-rail",
    introductions: "profile-introductions",
    credentials: "profile-credentials",
  },
  toasts: {
    success: "toasts-success",
    "error-retry": "toasts-error-retry",
    "info-banner": "toasts-info-banner",
    progress: "toasts-progress",
    undo: "toasts-undo",
    rich: "toasts-rich",
  },
  pricing: {
    "three-tier": "pricing-three-tier",
    "comparison-table": "pricing-comparison-table",
    "slider-seats": "pricing-slider-seats",
    "simple-card": "pricing-simple-card",
    "contact-sales": "pricing-contact-sales",
    "monthly-yearly": "pricing-monthly-yearly",
  },
  tours: {
    "welcome-carousel": "tours-welcome-carousel",
    spotlight: "tours-spotlight",
    "arrow-tooltip": "tours-arrow-tooltip",
    beacon: "tours-beacon",
    "inline-hint": "tours-inline-hint",
    checklist: "tours-checklist",
  },
  threads: {
    "inline-thread": "threads-inline-thread",
    "side-panel": "threads-side-panel",
    "comment-row": "threads-comment-row",
    "mention-popover": "threads-mention-popover",
    resolved: "threads-resolved",
    "compose-rich": "threads-compose-rich",
  },
};

export function getSourceFile(
  category: CategorySlug,
  design: string,
): string | undefined {
  return SOURCE_FILES[category]?.[design];
}
